# Generated by Django 4.0.6 on 2024-04-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0002_remove_disciplina_projeto_projeto_disciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='area_cientifica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCurso.areacientifica'),
        ),
    ]
