# Generated by Django 4.0.6 on 2024-04-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0003_alter_disciplina_area_cientifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='linguagens',
            field=models.ManyToManyField(blank=True, null=True, to='AppCurso.linguagemprogramacao'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linguagens',
            field=models.ManyToManyField(blank=True, null=True, to='AppCurso.linguagemprogramacao'),
        ),
    ]
