# Generated by Django 4.0.6 on 2024-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCurso', '0004_alter_disciplina_linguagens_alter_projeto_linguagens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos_Images/'),
        ),
    ]
