# Generated by Django 4.0.6 on 2024-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='genero',
            field=models.CharField(choices=[('Rock', 'Rock'), ('Pop', 'Pop'), ('Jazz', 'Jazz'), ('Blues', 'Blues'), ('Country', 'Country'), ('Hip Hop', 'Hip Hop'), ('Electronic', 'Electronic'), ('Classical', 'Classical'), ('Reggae', 'Reggae'), ('Funk', 'Funk'), ('Metal', 'Metal'), ('R&B', 'R&B')], max_length=100),
        ),
    ]
