# Generated by Django 4.0.6 on 2024-04-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0003_alter_musica_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='anoDeCriacao',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='banda',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
