# Generated by Django 4.0.6 on 2024-04-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0004_banda_anodecriacao_banda_nacionalidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banda',
            name='anoDeCriacao',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
