# Generated by Django 4.0.6 on 2024-04-19 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0006_alter_album_banda_alter_banda_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='musicas',
        ),
        migrations.AddField(
            model_name='musica',
            name='album',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='musicas', to='bandas.album'),
            preserve_default=False,
        ),
    ]
