# Generated by Django 4.0.6 on 2024-05-20 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandas', '0008_alter_musica_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='banda',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
