# Generated by Django 4.0.6 on 2024-04-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('artigos', models.ManyToManyField(related_name='artigos', to='blogue.artigo')),
            ],
        ),
    ]
