# Generated by Django 4.0.6 on 2024-04-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0002_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='artigos',
        ),
        migrations.AddField(
            model_name='artigo',
            name='categorias',
            field=models.ManyToManyField(related_name='categorias', to='blogue.categoria'),
        ),
    ]
