# Generated by Django 4.0.6 on 2024-04-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0003_remove_categoria_artigos_artigo_categorias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classificacao',
            name='valor',
            field=models.IntegerField(choices=[(1, '1'), (9, '5'), (3, '2'), (2, '1.5'), (4, '2.5'), (8, '4.5'), (5, '3'), (7, '4'), (6, '3.5')], default=1),
        ),
    ]
