# Generated by Django 4.0.6 on 2024-04-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0005_alter_classificacao_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='autores_imagens/'),
        ),
    ]
