# Generated by Django 4.0.6 on 2024-05-17 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogue', '0007_artigo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to=settings.AUTH_USER_MODEL),
        ),
    ]
