# Generated by Django 4.0.6 on 2024-05-17 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0010_alter_autor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='artigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blogue.artigo'),
        ),
    ]
